const languages = ['en', 'hi', 'ur'];
const shayariTags = [
	'aadmi-insaan',
	'ada',
	'akhbaar',
	'angdaai',
	'barish',
	'chaand',
	'dard',
	'deedar',
	'dhoka',
	'dil',
	'dost-dosti',
	'duniya',
	'farewell',
	'heart-break',
	'husn',
	'intizaar',
	'khamoshi',
	'kiss',
	'kitab',
	'lab',
	'maut',
	'mulaqat',
	'muskurahat',
	'phool',
	'sad',
	'safar',
	'sharab',
	'tanhai',
	'train',
	'visaal',
	'wafa',
	'waqt',
	'welcome',
	'yaad',
	'zindagi',
	'zulf',
];
const coupletTags = [
	'couplets-on-dua',
	'couplets-on-eyes',
	'couplets-on-love',
	'couplets-on-mirror',
	'couplets-on-seperation',
	'couplets-on-tasweer',
	'couplets-on-tears',
	'most-quoted-couplets',
	'motivational-couplets',
	'top-couplets-on-new-year',
];

export { languages, shayariTags, coupletTags };
